70B training data generation.
octoml/EAGLE pull request #3
Opened 2024-08-31 10:03 UTC by ita9naiwa

2024-09-03 15:25 UTC, adstraw reviewed
Please add top-level README to document all commands to 1) generate data 2) fine tune and 3) evaluate fine tune for both llama3.1-8b and llama3.1-70b.

2024-09-04 21:00 UTC, adstraw requested changes
It looks to me like the 8b and 70b training data scripts have converged with the addition of the --base-model-path argument, which I like.  Can we have just one script?  Left you some review comments for general cleanup

2024-09-04 21:00 UTC, adstraw commented on eagle/ge_data/ge_data_all_llama3-1-70Bchat.py
> +bigname="/opt/models/meta-llama-3.1-70b-instruct"
add --base-model-path arg

2024-09-04 21:00 UTC, adstraw commented on eagle/ge_data/ge_data_all_llama3-1chat.py
> +    ds1 = ds.select(range(0, 1000))
Do we want this hard-coded?

2024-09-04 21:00 UTC, adstraw commented on eagle/ge_data/ge_data_all_llama3-1-70Bchat.py
> +bigmodel.eval()
Is this second eval necessary?

2024-09-04 21:00 UTC, adstraw commented on eagle/ge_data/ge_data_all_llama3-1chat.py
> +    print(id)
delete?

2024-09-04 21:00 UTC, adstraw commented on eagle/model/cnets.py
> +
unnecessary whitespace

2024-09-04 21:00 UTC, adstraw commented on eagle/train/main.py
> +
unnecessary whitespace

2024-09-04 21:00 UTC, adstraw commented on llama-3-1-70B-multi-gpu-train-data-generation.md
> +nohup /opt/bin/cuda-reserve.py --num-gpus 6 accelerate launch --config_file=multi_gpu_acc.yaml  ge_data_all_llama3-1-70Bchat.py --start=0 --end=68000 --index=0 --gpu_index 0 --outdir ../../train-data
Is this file needed now that we have doc in the README?

2024-09-04 21:00 UTC, adstraw commented on eagle/train/main.py
> +        print("load ", index, "done")
delete?

2024-09-04 21:00 UTC, adstraw commented on eagle/ge_data/allocation.py
> +        print(command)
unnecessary whitespace diff

2024-09-04 22:59 UTC, ita9naiwa commented on llama-3-1-70B-multi-gpu-train-data-generation.md
> +nohup /opt/bin/cuda-reserve.py --num-gpus 6 accelerate launch --config_file=multi_gpu_acc.yaml  ge_data_all_llama3-1-70Bchat.py --start=0 --end=68000 --index=0 --gpu_index 0 --outdir ../../train-data
deleted

2024-09-04 22:59 UTC, ita9naiwa commented on eagle/train/main.py
> +        print("load ", index, "done")
deleted

2024-09-04 22:59 UTC, ita9naiwa commented on eagle/ge_data/allocation.py
> +        print(command)
fixed

2024-09-04 23:00 UTC, ita9naiwa commented on eagle/ge_data/ge_data_all_llama3-1chat.py
> +    print(id)
deleted

2024-09-04 23:01 UTC, ita9naiwa commented on eagle/ge_data/ge_data_all_llama3-1-70Bchat.py
> +bigmodel.eval()
I removed 70Bchat completely.

2024-09-04 23:01 UTC, ita9naiwa commented on eagle/ge_data/ge_data_all_llama3-1chat.py
> +    ds1 = ds.select(range(0, 1000))
removed.

2024-09-04 23:01 UTC, ita9naiwa commented on eagle/ge_data/ge_data_all_llama3-1-70Bchat.py
> +bigname="/opt/models/meta-llama-3.1-70b-instruct"
I removed 70Bchat completely.

2024-09-05 13:04 UTC, merged